In [3]:
from astropy.table import Table, Column
import astropy
import astropy.io.ascii as ascii
import sys
from copy import deepcopy
COSobs = Table([Column(name='date', data=['a','b']),
                Column(name='NUV exp.time', data=[1,2]),
                ])
latexdict = deepcopy(astropy.io.ascii.latexdicts['AA'])
latexdict['units'] = {'NUV exp.time':'s', 'FUV ext.time':'s'}
COSobs.write(sys.stdout, format='ascii.aastex', latexdict=latexdict,
             caption=r"\label{tab:obsCOS}Observations log of \emph{HST}/COS observations")

\begin{table}{cc}
\tablecaption{\label{tab:obsCOS}Observations log of \emph{HST}/COS observations}
\tablehead{\colhead{date} & \colhead{NUV exp.time}\\ \colhead{ } & \colhead{s}}
\startdata
a & 1 \\
b & 2
\enddata
\end{table}


In [1]:
from astropy.table import Table
a=[1,3,4]
b=[2.0,4.0,8.2]
c=['x','y','z']

In [2]:
t=Table([a,b,c],names=('a','b','c'),meta={'name':'first table'})

In [3]:
t

<Table length=3>
  a      b     c  
int64 float64 str1
----- ------- ----
    1     2.0    x
    3     4.0    y
    4     8.2    z

In [5]:
data_rows = [(1, 2.0, 'x'),
             (4, 5.0, 'y'),
             (5, 8.2, 'z')]

In [6]:
data_rows

[(1, 2.0, 'x'), (4, 5.0, 'y'), (5, 8.2, 'z')]

In [9]:
a=data_rows[0]

In [10]:
?a

In [11]:
t['a']

<Column name='a' dtype='int64' length=3>
1
3
4

In [12]:
t['b'].unit='s'

In [13]:
t

<Table length=3>
  a      b     c  
         s        
int64 float64 str1
----- ------- ----
    1     2.0    x
    3     4.0    y
    4     8.2    z

In [14]:
t.info

/Users/jituo/anaconda/lib/python2.7/site-packages/astropy-1.1.2-py2.7-macosx-10.5-x86_64.egg/astropy/table/column.py:268: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return self.data.__eq__(other)


<Table length=3>
name  dtype  unit
---- ------- ----
   a   int64     
   b float64    s
   c    str1     

In [15]:
t['b'].quantity

<Quantity [ 2. , 4. , 8.2] s>

In [28]:
t['b'].format='7.2f'

In [26]:
t

<Table length=3>
  a      b     c  
         s        
int64 float64 str1
----- ------- ----
    1    2.00    x
    3    4.00    y
    4    8.20    z

In [29]:
print(t)

 a     b     c 
       s       
--- ------- ---
  1    2.00   x
  3    4.00   y
  4    8.20   z


In [30]:
t.show_in_browser()  

In [31]:
 print(t[0:2]) 

 a     b     c 
       s       
--- ------- ---
  1    2.00   x
  3    4.00   y


In [32]:
a=[1,2,3,4,5]

In [33]:
a[0:2]

[1, 2]

In [34]:
t['d'] = [1, 2, 3]

In [35]:
t

<Table length=3>
  a      b     c     d  
         s              
int64 float64 str1 int64
----- ------- ---- -----
    1    2.00    x     1
    3    4.00    y     2
    4    8.20    z     3

In [36]:
del t['c']

In [37]:
t

<Table length=3>
  a      b      d  
         s         
int64 float64 int64
----- ------- -----
    1    2.00     1
    3    4.00     2
    4    8.20     3

In [38]:
t.rename_column('a','A')

In [39]:
t

<Table length=3>
  A      b      d  
         s         
int64 float64 int64
----- ------- -----
    1    2.00     1
    3    4.00     2
    4    8.20     3

In [40]:
t = Table([a, b, c], names=('a', 'b', 'c'), masked=True, dtype=('i4', 'f8', 'S1'))

ValueError: Inconsistent data column lengths: set([3, 5])

In [41]:
t

<Table length=3>
  A      b      d  
         s         
int64 float64 int64
----- ------- -----
    1    2.00     1
    3    4.00     2
    4    8.20     3

In [43]:
t = Table(t, masked=True)

In [44]:
t

<Table masked=True length=3>
  A      b      d  
         s         
int64 float64 int64
----- ------- -----
    1    2.00     1
    3    4.00     2
    4    8.20     3

In [46]:
t['A'].mask=[True,True,False]

In [47]:
t

<Table masked=True length=3>
  A      b      d  
         s         
int64 float64 int64
----- ------- -----
   --    2.00     1
   --    4.00     2
    4    8.20     3

In [48]:
from astropy.time import Time
from astropy.coordinates import SkyCoord
tm = Time(['2000:002', '2002:345'])
sc = SkyCoord([10, 20], [-45, +40], unit='deg')

In [49]:
tm

<Time object: scale='utc' format='yday' value=['2000:002:00:00:00.000' '2002:345:00:00:00.000']>

In [50]:
t = Table([tm, sc], names=['time', 'skycoord'])

In [51]:
t

<Table length=2>
         time          skycoord 
                       deg,deg  
        object          object  
--------------------- ----------
2000:002:00:00:00.000 10.0,-45.0
2002:345:00:00:00.000  20.0,40.0

In [55]:
from astropy.table import QTable
import astropy.units as u
t = QTable()
t['dist'] = [1, 2] * u.m
t['velocity'] = [3, 4] * u.m / u.s
t

<QTable length=2>
  dist  velocity
   m     m / s  
float64 float64 
------- --------
    1.0      3.0
    2.0      4.0

In [56]:
 from astropy.table import Table
obs = Table.read("""name    obs_date    mag_b  mag_v
                    M31     2012-01-02  17.0   17.5
                    M31     2012-01-02  17.1   17.4
                   M101    2012-01-02  15.1   13.5
                  M82     2012-02-14  16.2   14.5
              M31     2012-02-14  16.9   17.3
                M82     2012-02-14  15.2   15.5
                M101    2012-02-14  15.0   13.6
                    M82     2012-03-26  15.7   16.5
                   M101    2012-03-26  15.1   13.5
                   M101    2012-03-26  14.8   14.3
                   """, format='ascii')

In [57]:
obs

<Table length=10>
name  obs_date   mag_b   mag_v 
str4   str10    float64 float64
---- ---------- ------- -------
 M31 2012-01-02    17.0    17.5
 M31 2012-01-02    17.1    17.4
M101 2012-01-02    15.1    13.5
 M82 2012-02-14    16.2    14.5
 M31 2012-02-14    16.9    17.3
 M82 2012-02-14    15.2    15.5
M101 2012-02-14    15.0    13.6
 M82 2012-03-26    15.7    16.5
M101 2012-03-26    15.1    13.5
M101 2012-03-26    14.8    14.3

In [58]:
obs_by_name=obs.group_by('name')

In [61]:
print(obs_by_name)

name  obs_date  mag_b mag_v
---- ---------- ----- -----
M101 2012-01-02  15.1  13.5
M101 2012-02-14  15.0  13.6
M101 2012-03-26  15.1  13.5
M101 2012-03-26  14.8  14.3
 M31 2012-01-02  17.0  17.5
 M31 2012-01-02  17.1  17.4
 M31 2012-02-14  16.9  17.3
 M82 2012-02-14  16.2  14.5
 M82 2012-02-14  15.2  15.5
 M82 2012-03-26  15.7  16.5


In [62]:
 print(obs.group_by(['name', 'obs_date']).groups.keys)

name  obs_date 
---- ----------
M101 2012-01-02
M101 2012-02-14
M101 2012-03-26
 M31 2012-01-02
 M31 2012-02-14
 M82 2012-02-14
 M82 2012-03-26


In [63]:
print(obs_by_name.groups[1])

name  obs_date  mag_b mag_v
---- ---------- ----- -----
 M31 2012-01-02  17.0  17.5
 M31 2012-01-02  17.1  17.4
 M31 2012-02-14  16.9  17.3


In [66]:
obs_by_name.groups[1]

<Table length=3>
name  obs_date   mag_b   mag_v 
str4   str10    float64 float64
---- ---------- ------- -------
 M31 2012-01-02    17.0    17.5
 M31 2012-01-02    17.1    17.4
 M31 2012-02-14    16.9    17.3

In [67]:
?itertools

Object `itertools` not found.


In [69]:
?izip

In [71]:
import numpy as np

In [72]:
from itertools import izip

In [73]:
year = np.linspace(2000.0, 2010.0, 200)

In [74]:
 t = (4, 5.5, "spam")

In [75]:
t[0]

4

In [76]:
t[0]=4

TypeError: 'tuple' object does not support item assignment

In [77]:
a=[1,2,3]

In [78]:
a+3

TypeError: can only concatenate list (not "int") to list

In [80]:
b=a+[3]

In [81]:
b

[1, 2, 3, 3]

In [84]:
from astropy.io import ascii
table = """
col1 & col2
  1  & 'hi there'
  3  & world
"""
ascii.read(table)

<Table length=2>
 col1  &     col2  
int64 str1   str8  
----- ---- --------
    1    & hi there
    3    &    world

In [87]:
table = """
col1,col2,col3
1,hello world,2.5
3,again,5.0"""
dat = ascii.read(table)

dat

<Table length=2>
 col1     col2      col3 
int64    str11    float64
----- ----------- -------
    1 hello world     2.5
    3       again     5.0

In [88]:
table = """
col1,col2,col3
1,hello world,2.5
3,again,5.0"""
dat = ascii.read(table)

In [89]:
?dat

In [90]:
?table

In [98]:
dat = ascii.read('http://www.ucolick.org/~xavier/SDSSDLA/tab_dr5.html',
                 format='html',
                 htmldict={'table_id':2},  # Get data from the second table
                 fill_values=('', '-1'),   # Fill blank entries with -1
                 header_start=0,           # Row 0 is header with column names
                 data_start=1)             # Row 1 is start of table data

In [93]:
?dat

In [101]:
dat['Name']

<MaskedColumn name='Name' dtype='str19' length=1760>
J000238.41-101149.8
J000536.38+135949.4
J001115.23+144601.8
J001115.23+144601.8
J001134.52+155137.4
J001134.52+155137.4
J001240.57+135236.7
J001328.21+135828.0
J001328.21+135827.9
J001918.43+150611.3
J002614.69+143105.2
J002614.69+143105.2
                ...
J232025.08-104226.7
J232115.48+142131.5
J233446.40-090812.3
J233838.22-003513.7
J234033.70-005636.9
J234352.62+141014.6
J234856.48-104131.2
J235028.85+151626.7
J235028.85+151626.7
J235057.87-005209.9
J235057.87-005209.9
J235702.54-004824.0

In [97]:
dat.colnames

['Generic Name',
 'R.A. (J2000) hh:mm:ss.s',
 'Dec. (J2000) dd:mm:ss.s',
 'z',
 'Class',
 'X-ray Features',
 'Assoc. optical',
 'Assoc. radio',
 'PA w.r.t core',
 'Dist. (H=71) (Mpc)',
 'kpc/" (H=71)']

In [102]:
from astropy.extern.six.moves.urllib import request
url = 'http://python4astronomers.github.com/_downloads/myidlfile.sav'
open('myidlfile.sav', 'wb').write(request.urlopen(url).read())

NameError: name 'ls' is not defined

In [103]:
ls

DLASurvey_examples.ipynb  data_2_1                  make_data*
EWtab.tex                 data_2_5                  myidlfile.sav
Lya_analysis.ipynb        data_4_1                  note_test.ipynb
UVES/                     data_4_5                  py4ast/
Untitled.ipynb            find_PDLAs.ipynb          untitled.txt
XKCD_plots.ipynb          linked_brushing.ipynb


In [104]:
from scipy.io.idl import readsav
data = readsav('myidlfile.sav')

/Users/jituo/anaconda/lib/python2.7/site-packages/scipy/io/idl.py:167: UserWarning: warning: empty strings are now set to '' instead of None
  warnings.warn("warning: empty strings are now set to '' instead of None")


In [105]:
data

{'str': rec.array([ (12.520000457763672, -27.219999313354492, array([  8.69999981,   8.60000038,   9.60000038,  10.10000038,  11.5       ], dtype=float32))], 
           dtype=[(('ra', 'RA'), '>f4'), (('dec', 'DEC'), '>f4'), (('fluxes', 'FLUXES'), 'O')]),
 'x': array([ 0.        ,  0.33333334,  0.66666669,  1.        ,  1.33333337,
         1.66666663,  2.        ,  2.33333325,  2.66666675,  3.        ,
         3.33333325,  3.66666675,  4.        ,  4.33333349,  4.66666651,
         5.        ,  5.33333349,  5.66666651,  6.        ,  6.33333349,
         6.66666651,  7.        ,  7.33333349,  7.66666651,  8.        ], dtype=float32),
 'y': array([ 0.        ,  0.32745016,  0.62514514,  0.88137364,  1.09861231,
         1.2837956 ,  1.44363546,  1.58348906,  1.70741141,  1.8184464 ,
         1.91889644,  2.01052713,  2.0947125 ,  2.17253971,  2.24487901,
         2.31243849,  2.37579918,  2.43544436,  2.4917798 ,  2.54514909,
         2.59584522,  2.64412069,  2.69019413,  2.73425555, 

In [106]:
?data

In [110]:
data.viewkeys()

dict_keys(['y', 'x', 'str'])

In [111]:
data.str

rec.array([ (12.520000457763672, -27.219999313354492, array([  8.69999981,   8.60000038,   9.60000038,  10.10000038,  11.5       ], dtype=float32))], 
          dtype=[(('ra', 'RA'), '>f4'), (('dec', 'DEC'), '>f4'), (('fluxes', 'FLUXES'), 'O')])

In [112]:
from astropy import coordinates as coord

In [113]:
from astropy import units as u

In [115]:
coord.ICRS('00h42m44.3s +41d16m9s')

<SkyCoord (ICRS): (ra, dec) in deg
    (10.68458333, 41.26916667)>

In [116]:
a=[[ 1., 0., 0.],
 [ 0., 1., 2.]]

In [117]:
?a

In [118]:
a[0]

[1.0, 0.0, 0.0]

In [119]:
 a = np.arange(15).reshape(3, 5)

In [120]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
Table(a)

<Table length=3>
 col0  col1  col2  col3  col4
int64 int64 int64 int64 int64
----- ----- ----- ----- -----
    0     1     2     3     4
    5     6     7     8     9
   10    11    12    13    14

In [124]:
a.shape?

In [129]:
a=np.ones( (2,3,4), dtype=np.int16 )        

In [130]:
?a

In [131]:
b = np.random.random((2,3))

In [132]:
b

array([[ 0.15114787,  0.00471185,  0.78474789],
       [ 0.36271373,  0.87853284,  0.00661822]])

In [133]:
 a = np.ones((2,3), dtype=int)

In [134]:
a+=b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [135]:
b+=a

In [136]:
b

array([[ 1.15114787,  1.00471185,  1.78474789],
       [ 1.36271373,  1.87853284,  1.00661822]])

In [137]:
b = np.arange(12).reshape(3,4)

In [138]:
 b.sum(axis=0)

array([12, 15, 18, 21])

In [139]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [143]:
a = np.floor(10*np.random.random((2,2)))

In [144]:
a = np.floor(10*np.random.random((2,2)))

In [145]:
 b = np.floor(10*np.random.random((2,2)))

In [146]:
a

array([[ 2.,  9.],
       [ 0.,  0.]])

In [147]:
b

array([[ 3.,  3.],
       [ 5.,  9.]])

In [148]:
a = np.arange(12)

In [149]:
c = a.view()

In [150]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
?c

In [152]:
c.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [154]:
c.shape=2,6

In [157]:
a.shape=3,4

In [158]:
 s = a[ : , 1:3] 

In [163]:
 s = a[ : , 1:3] 

In [164]:
s[:,:]=10

In [165]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [8]:
from astropy import units as u
restfreq=2796.35*u.angstrom

In [9]:
restfreq

<Quantity 2796.35 Angstrom>

In [10]:
(2803.53*u.angstrom).to(u.km / u.s, equivalencies=u.doppler_optical(restfreq))

<Quantity 769.7569504675822 km / s>

In [11]:
from enthought.mayavi import mlab

ImportError: No module named enthought.mayavi

In [14]:
from mayavi import mlab
import numpy as np

In [15]:
x, y, z, value = np.random.random((4, 40))
mlab.points3d(x, y, z, value)

In [1]:
import pyCloudy as pc

warng pyCloudy config: pyCloudy works better with PyNeb


RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pc.log_.level = 3

In [3]:
dir_ = './'

In [4]:
# Define some parameters of the model:
model_name = 'model_1'
full_model_name = '{0}{1}'.format(dir_, model_name)
dens = 2. #log cm-3
Teff = 45000. #K
qH = 47. #s-1
r_min = 5e17 #cm
dist = 1.26 #kpc

In [5]:

# these are the commands common to all the models (here only one ...)
options = ('no molecules',
            'no level2 lines',
            'no fine opacities',
            'atom h-like levels small',
            'atom he-like levels small',
            'COSMIC RAY BACKGROUND',
            'element limit off -8',
            'print line optical depth', 
            )

In [6]:
emis_tab = ['H  1  4861',
            'H  1  6563',
            'He 1  5876',
            'N  2  6584',
            'O  1  6300',
            'O II  3726',
            'O II  3729',
            'O  3  5007',
            'TOTL  4363',
            'S II  6716',
            'S II 6731',
            'Cl 3 5518',
            'Cl 3 5538',
            'O  1 63.17m',
            'O  1 145.5m',
            'C  2 157.6m']

In [7]:
abund = {'He' : -0.92, 'C' : 6.85 - 12, 'N' : -4.0, 'O' : -3.40, 'Ne' : -4.00, 
         'S' : -5.35, 'Ar' : -5.80, 'Fe' : -7.4, 'Cl' : -7.00}

In [8]:
c_input = pc.CloudyInput(full_model_name)

In [9]:
c_input.set_BB(Teff = Teff, lumi_unit = 'q(H)', lumi_value = qH)


In [12]:
c_input.set_cste_density(dens)
import numpy as np

In [13]:
# Defining the inner radius. A second parameter would be the outer radius (matter-bounded nebula).
c_input.set_radius(r_in=np.log10(r_min))
c_input.set_abund(ab_dict = abund, nograins = True)
c_input.set_other(options)
c_input.set_iterate() # (0) for no iteration, () for one iteration, (N) for N iterations.
c_input.set_sphere() # () or (True) : sphere, or (False): open geometry.
c_input.set_emis_tab(emis_tab) # better use read_emis_file(file) for long list of lines, where file is an external file.
c_input.set_distance(dist=dist, unit='kpc', linear=True) # unit can be 'kpc', 'Mpc', 'parsecs', 'cm'. If linear=False, the distance is in log.

In [14]:
c_input.print_input(to_file = True, verbose = False)

     CloudyInput: Input writen in ./model_1.in


In [15]:
pc.log_.message('Running {0}'.format(model_name), calling = 'test1')

     test1: Running model_1


In [16]:
c_input.run_cloudy()

     run_cloudy: running: cd . ;  cloudy.exe
     run_cloudy: ending: cd . ;  cloudy.exe
